version: '2'
services:
  origin:
    build:
      context: ./
      dockerfile: Dockerfile.origin
    volumes:
      - ./:/usr/lib/origin
    depends_on:
      - postgres
      - redis-sidekiq
      - redis-objects
      - redis-cache
      - redis-redlock
      - proxy
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=postgres
      - REDIS_CACHE_URL=redis://redis-cache:6379/0
      - REDIS_CACHE_POOL_SIZE=20
      - REDIS_SIDEKIQ_URL=redis://redis-sidekiq:6379/1
      - REDIS_SIDEKIQ_SERVER_POOL_SIZE=10
      - REDIS_SIDEKIQ_CLIENT_POOL_SIZE=10
      - REDIS_OBJECTS_URL=redis://redis-objects:6379/1
      - REDIS_OBJECTS_POOL_SIZE=20
      - REDIS_REDLOCK_URL=redis://redis-redlock:6379/2
      - REDIS_REDLOCK_POOL_SIZE=20
      - RAILS_MAX_THREADS=4
      - WEB_CONCURRENCY=2
      - RAILS_EMAIL_HOST=localhost
      - RAILS_EMAIL_USER=noreply
      - ORIGIN_LOCATION=http://origin.poutineer.local
      - WWW_LOCATION=http://www.poutineer.local
      - RAILS_HOST=origin.poutineer.local
      - VIRTUAL_HOST=origin.poutineer.local
      - BUGSNAG_API_PRIVATE
      - ORIGIN_ENCRYPTION_PRIVATE
      - ORIGIN_ENCRYPTION_SALT
      - RAILS_SESSION_SECRET
  postgres:
    image: postgres:9.6-alpine
    environment:
      - VIRTUAL_HOST=postgres.poutineer.local
  redis-sidekiq:
    image: redis:3.2.11-alpine
    environment:
      - VIRTUAL_HOST=redis-sidekiq.poutineer.local
  redis-objects:
    image: redis:3.2.11-alpine
    environment:
      - VIRTUAL_HOST=redis-objects.poutineer.local
  redis-cache:
    image: redis:3.2.11-alpine
    environment:
      - VIRTUAL_HOST=redis-cache.poutineer.local
  redis-redlock:
    image: redis:3.2.11-alpine
    environment:
      - VIRTUAL_HOST=redis-redlock.poutineer.local
  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/:/etc/nginx/conf.d/
